### ISSUE TITLE
fix: better-sqlite3@11.10.0 incompatible with Node 26 — v8 API removed (GetPrototype, GetIsolate, This)

### ISSUE THREAD

**Issue by chirag127** [JuliusBrussee/cavemem#53]
## Problem

cavemem v0.2.1 ships `better-sqlite3@11.10.0` which fails to compile on Node 26.4.0:

\`\`\`
error C2039: 'GetPrototype': is not a member of 'v8::Object'
error C2039: 'GetIsolate': is not a member of 'v8::Context'
error C2039: 'This': is not a member of 'v8::PropertyCallbackInfo<v8::Value>'
\`\`\`

These V8 APIs were removed in Node 26. `better-sqlite3@12.x` updated to the new V8 interface and supports Node 26.

## Fix

Bump `better-sqlite3` to `^12.0.0` in `package.json`.

## Environment

- Node: v26.4.0 (Current)
- cavemem: 0.2.1
- better-sqlite3 bundled: 11.10.0

**Comment by JuliusBrussee** [comment]
Fixed in a52553d — better-sqlite3 bumped to ^12.0.0 exactly as you suggested. Ships in v0.3.0.
